spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: houndingtutorial@gmail.com
    password: Hound1997c
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
  jpa:
    hibernate:
      ddl-auto: update
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/houndingstory?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: springuser
    password: ThePassword
